const data = {
  //small letters
  admin: [
    '0x9d95bcaa5b609fa97a7ec860bec115aa94f85ba9',
    '0x0902cb364e49101f4ab5d4ffde5035973e728d3f',
    '0xe3342d6522ad72f65D6b23f19b17e3fb12161f90',
    '0xe26d51bd25617bad4f1f7ffa2c11349d2c645776',
  ], //put in small letters
  products: [
    {
      name: 'Gen 2 #620',
      slug: 'raffle-project-godjira',
      type: 'Raffle',
      brand: 'Project Godjira',
      currency: 'UCD',
      image: '/images/nft-godjira.png',
      price: 500,
      countInStock: 100,
    },
    {
      name: 'Whitelist',
      slug: 'whitelist-mindblowon',
      type: 'whitelist',
      brand: 'Mindblowon',
      currency: 'UCD',
      image: '/images/nft-mindblowon.png',
      price: 200,
      countInStock: 10,
    },
    {
      name: 'Whitelist',
      slug: 'whitelist-project-pxn',
      type: 'whitelist',
      brand: 'Project PXN',
      currency: 'UCD',
      image: '/images/nft-PXN.png',
      price: 300,
      countInStock: 5,
    },
    {
      name: 'Whitelist',
      slug: 'whitelist-shamanzs',
      type: 'whitelist',
      brand: 'Shamanzs',
      currency: 'UCD',
      image: '/images/nft-shamanzs.png',
      price: 200,
      countInStock: 20,
    },
    {
      name: 'Gen 2 Whitelist',
      slug: 'whitelist-clementines-nightmare',
      type: 'whitelist',
      brand: "Clementine's Nightmare",
      currency: 'UCD',
      image: '/images/nft-clementines.png',
      price: 5,
      countInStock: 5,
    },
    {
      name: 'Whitelist',
      slug: 'whitelist-broskees',
      type: 'whitelist',
      brand: 'Broskees',
      currency: 'UCD',
      image: '/images/nft-broskees.png',
      price: 200,
      countInStock: 10,
    },
    {
      name: 'Whitelist',
      slug: 'whitelist-tasty-bones',
      type: 'whitelist',
      brand: 'Tasty Bones',
      currency: 'UCD',
      image: '/images/nft-tastybones.png',
      price: 200,
      countInStock: 5,
    },
  ],
};
export default data;
