const data = {
  //small letters
  admin: ["0x9d95bcaa5b609fa97a7ec860bec115aa94f85ba9"], //put in small letters
  products: [
    {
      name: "UU Shirt",
      slug: "uu-shirt",
      type: "Physical",
      brand: "Uninterested Unicorns",
      currency: "UCD",
      image: "/images/shirt1.jpg",
      isFeatured: true,
      featuredImage: "/images/banner1.jpg",
      price: 70,
      countInStock: 20,
      description: "A UU shirt",
    },
    {
      name: "Whitelist Spot UCD",
      slug: "whitelist-spot-ucd",
      type: "Virtual",
      brand: "Uninterested Unicorns",
      currency: "UCD",
      image: "/images/shirt2.jpg",
      isFeatured: true,
      featuredImage: "/images/banner2.jpg",
      price: 80,
      countInStock: 10,
      description: "A whitelist spot",
    },
    {
      name: "SS Shirt",
      slug: "ss-shirt",
      type: "Physical",
      brand: "Shogun Samurai",
      currency: "SHO",
      image: "/images/shirt3.jpg",
      price: 90,
      countInStock: 5,
      description: "A SS shirt",
    },
    {
      name: "Whitelist Spot SHO",
      slug: "whitelist-spot-sho",
      type: "Virtual",
      brand: "Shogun Samurai",
      currency: "SHO",
      image: "/images/pants1.jpg",
      price: 100,
      countInStock: 10,
      description: "A whitelist spot",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      type: "Physical",
      brand: "Shogun Samurai",
      currency: "SHO",
      image: "/images/pants2.jpg",
      price: 95,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      type: "Physical",
      brand: "Shogun Samurai",
      currency: "SHO",
      image: "/images/pants3.jpg",
      price: 75,
      countInStock: 20,
      description: "A popular pants",
    },
  ],
};
export default data;
